"""초기 카드 시드 데이터 (skill_meta.description 기반 버전)."""
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from models.card import CardTemplate

SEED_CARDS = [{'hero_key': 'reinhardt',
  'name': '라인하르트',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 6},
  'skill_meta': {'passive': {'name': '방벽 방패', 'description': '내구도 15의 방벽으로 아군을 보호하며 도발 효과를 가진다.'},
                 'skill_1': {'name': '화염강타', 'cooldown': 0, 'description': '방벽류 방어 스킬을 무시하고 6 피해를 준다.'}},
  'extra': {'barrier_hp': 15}},
 {'hero_key': 'winston',
  'name': '윈스턴',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 4},
  'skill_meta': {'skill_1': {'name': '테슬라 캐논', 'cooldown': 0, 'description': '테슬라 캐논으로 4 피해를 준다.'},
                 'skill_2': {'name': '방벽 생성기', 'cooldown': 0, 'description': '내구도 5의 영구 방벽을 자신 또는 다른 아군 역할군에 부여한다.'}},
  'extra': {'barrier_hp': 5}},
 {'hero_key': 'dva',
  'name': '디바',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5, 'skill_2': [8, 5, 3, 1]},
  'skill_meta': {'passive': {'name': '메카 파괴', 'description': '메카가 파괴되면 송하나로 변경되고, 송하나 상태로 2턴 생존하면 메카를 다시 호출한다.'},
                 'skill_1': {'name': '부스터',
                             'cooldown': 0,
                             'description': '상대 탱커를 패싱하고 6 피해를 준다. 대신 다음 턴에는 자신도 패싱당할 수 있다.'},
                 'skill_2': {'name': '마이크로 미사일', 'cooldown': 0, 'description': '거리 1/2/3/4에서 각각 8/5/3/1 피해를 준다.'}},
  'extra': {'hana_hp': 5}},
 {'hero_key': 'zarya',
  'name': '자리야',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 0, 'skill_2': 5},
  'skill_meta': {'skill_1': {'name': '입자 방벽',
                             'cooldown': 0,
                             'description': '첫 공격을 무효화한다. 공격을 받으면 다음 턴 입자포 피해가 증가하고, 맞지 않으면 한 턴 유지 후 파괴된다.'},
                 'skill_2': {'name': '입자포', 'cooldown': 0, 'description': '기본 5 피해를 주며, 입자 방벽이 공격받았다면 추가 피해를 얻는다.'}},
  'extra': {'particle_bonus': 3}},
 {'hero_key': 'wrecking_ball',
  'name': '레킹볼',
  'role': 'tank',
  'hp': 25,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 6},
  'skill_meta': {'passive': {'name': '갈고리', 'description': '스킬을 사용하기 전 본대와 사이드를 오갈 수 있다.'},
                 'skill_1': {'name': '파일드라이버', 'cooldown': 0, 'description': '파일드라이버로 6 피해를 준다.'}}},
 {'hero_key': 'junkerqueen',
  'name': '정커퀸',
  'role': 'tank',
  'hp': 22,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'skill_1': {'name': '톱니칼', 'cooldown': 0, 'description': '3 피해를 주고 대상 하나를 한 칸 앞으로 끌어당긴다.'},
                 'skill_2': {'name': '지휘의 외침', 'cooldown': 0, 'description': '주위 아군 모두에게 추가 체력 2를 부여한다.'}},
  'extra': {'shout_extra_hp': 2}},
 {'hero_key': 'doomfist',
  'name': '둠피스트',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': [5, 3], 'skill_1_empowered': 6},
  'skill_meta': {'skill_1': {'name': '로켓 펀치',
                             'cooldown': 0,
                             'description': '앞 대상에게 5, 뒤 한 칸의 대상에게 3 피해를 준다. 강화 상태라면 둘 모두에게 6 피해를 준다.'},
                 'skill_2': {'name': '파워블락', 'cooldown': 0, 'description': '받는 피해를 줄이고 강화된 로켓 펀치를 사용할 수 있게 한다.'}}},
 {'hero_key': 'sigma',
  'name': '시그마',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '실험용 방벽', 'cooldown': 0, 'description': '도발 효과를 지닌 내구도 10의 방벽을 설치하거나 내린다.'},
                 'skill_2': {'name': '초재생', 'cooldown': 0, 'description': '실험용 방벽의 내구도를 5 회복한다.'}},
  'extra': {'barrier_hp': 10, 'regen_amount': 5}},
 {'hero_key': 'ramattra',
  'name': '라마트라',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 2},
  'skill_meta': {'skill_1': {'name': '탐식의 소용돌이',
                             'cooldown': 0,
                             'description': '일반 폼에서만 사용 가능. 한 역할군에 2 피해를 주고 사거리를 1 감소시킨다.'},
                 'skill_2': {'name': '폼 체인지',
                             'cooldown': 0,
                             'description': '일반 폼과 네메시스 폼을 전환한다. 네메시스 폼 전환 시 추가 체력을 얻는다.'},
                 'skill_3': {'name': '막기', 'cooldown': 0, 'description': '네메시스 폼에서만 사용 가능. 한 턴 동안 받는 피해를 50% 감소시킨다.'}},
  'extra': {'nemesis_bonus_hp': 10, 'block_reduction': 50}},
 {'hero_key': 'domina',
  'name': '도미나',
  'role': 'tank',
  'hp': 22,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'skill_1': {'name': '수정 발사', 'cooldown': 0, 'description': '탱커를 무시하고 상대 딜러 라인 전체에 3 피해를 준다.'},
                 'skill_2': {'name': '방벽 배열', 'cooldown': 0, 'description': '자신에게 내구도 4의 방벽을 부여하고 도발 효과를 얻는다.'}},
  'extra': {'barrier_hp': 4}},
 {'hero_key': 'roadhog',
  'name': '로드호그',
  'role': 'tank',
  'hp': 25,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 0, 'skill_2': 5},
  'skill_meta': {'skill_1': {'name': '갈고리',
                             'cooldown': 0,
                             'description': '한 칸 먼 적까지 끌어당긴다. 적중한 대상은 그 턴 동안 아군이 사거리와 무관하게 공격할 수 있다.'},
                 'skill_2': {'name': '숨돌리기', 'cooldown': 0, 'description': '체력이 15 이하일 때 사용 가능. 자신을 5 회복한다.'}},
  'extra': {'heal_threshold': 15}},
 {'hero_key': 'bastion',
  'name': '바스티온',
  'role': 'dealer',
  'hp': 12,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 10, 'skill_2': 2},
  'skill_meta': {'skill_1': {'name': '설정: 강습', 'cooldown': 0, 'description': '10 피해를 주지만 연속으로 사용할 수 없다.'},
                 'skill_2': {'name': '설정: 수색', 'cooldown': 0, 'description': '기본 모드 공격으로 2 피해를 준다.'}}},
 {'hero_key': 'freja',
  'name': '프레야',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 0, 'skill_2': 8},
  'skill_meta': {'skill_1': {'name': '상승기류',
                             'cooldown': 0,
                             'description': '3턴 동안 에어본 상태가 된다. 에어본 중에는 한 칸을 무시하고 공격할 수 있지만, 자신이 받는 사거리는 1 감소한다.'},
                 'skill_2': {'name': '정조준', 'cooldown': 0, 'description': '에어본 상태에서만 사용 가능. 8 피해를 준 뒤 착지한다.'}}},
 {'hero_key': 'tracer',
  'name': '트레이서',
  'role': 'dealer',
  'hp': 6,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'passive': {'name': '점멸', 'description': '상대 레벨을 한 칸 무시하고 공격할 수 있다.'},
                 'skill_1': {'name': '펄스 쌍권총', 'cooldown': 0, 'description': '펄스 쌍권총으로 5 피해를 준다.'},
                 'skill_2': {'name': '역행', 'cooldown': 0, 'description': '한 턴 전 체력 상태로 되돌아간다.'}}},
 {'hero_key': 'widowmaker',
  'name': '위도우메이커',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 99,
  'description': '',
  'skill_damages': {'skill_1': 4},
  'skill_meta': {'passive': {'name': '명사수', 'description': '거리 제한의 영향을 받지 않고 공격할 수 있다.'},
                 'skill_1': {'name': '죽음의 입맞춤',
                             'cooldown': 0,
                             'description': '기본 4 피해를 주며, 25% 확률로 헤드샷이 발동해 3배 피해를 준다.'}}},
 {'hero_key': 'hanzo',
  'name': '한조',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 99,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'passive': {'name': '명사수', 'description': '거리 제한의 영향을 받지 않고 공격할 수 있다.'},
                 'skill_1': {'name': '폭풍활', 'cooldown': 0, 'description': '기본 5 피해를 주며, 25% 확률로 헤드샷이 발동해 2배 피해를 준다.'}}},
 {'hero_key': 'venture',
  'name': '벤처',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 7, 'skill_2': 3},
  'skill_meta': {'skill_1': {'name': '잠복',
                             'cooldown': 0,
                             'description': '타게팅에서 제외되고 다음 자신의 턴에 공격한다. 한 칸을 무시해 공격할 수 있으며 연속 사용은 불가하다.'},
                 'skill_2': {'name': '스마트 굴착기', 'cooldown': 0, 'description': '스마트 굴착기로 3 피해를 준다.'}}},
 {'hero_key': 'sombra',
  'name': '솜브라',
  'role': 'dealer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'passive': {'name': '기회주의자', 'description': '카드를 내려놓을 때 상대 설치 스킬의 유무를 확인한다.'},
                 'skill_1': {'name': '기관단총', 'cooldown': 0, 'description': '기관단총으로 5 피해를 준다.'},
                 'skill_2': {'name': '은신', 'cooldown': 0, 'description': '한 턴 동안 타게팅에서 제외되고 체력을 3 회복한다. 연속 사용은 불가하다.'}},
  'extra': {'stealth_heal': 3}},
 {'hero_key': 'echo',
  'name': '에코',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': [4, 4], 'skill_2': 6},
  'skill_meta': {'skill_1': {'name': '점착폭탄', 'cooldown': 0, 'description': '점착 피해 4와 다음 턴 폭발 피해 4를 준다.'},
                 'skill_2': {'name': '광선집중', 'cooldown': 0, 'description': '기본 6 피해를 주며, 대상이 반피 이하라면 1.5배 피해를 준다.'}}},
 {'hero_key': 'cassidy',
  'name': '캐서디',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 3,
  'description': '',
  'skill_damages': {'skill_1': [8, 4, 2]},
  'skill_meta': {'skill_1': {'name': '난사', 'cooldown': 0, 'description': '거리 1/2/3에서 각각 8/4/2 피해를 준다.'}}},
 {'hero_key': 'reaper',
  'name': '리퍼',
  'role': 'dealer',
  'hp': 12,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 3,
  'description': '',
  'skill_damages': {'skill_1': [8, 4, 1]},
  'skill_meta': {'skill_1': {'name': '헬파이어 샷건', 'cooldown': 0, 'description': '거리 1/2/3에서 각각 8/4/1 피해를 준다.'}}},
 {'hero_key': 'mei',
  'name': '메이',
  'role': 'dealer',
  'hp': 15,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'passive': {'name': '급속 빙결',
                             'description': '치명 피해를 받으면 HP 1의 빙결 상태가 되고, 다음 자신의 턴 시작에 반피(반올림)로 부활한다.'},
                 'skill_1': {'name': '냉각총', 'cooldown': 0, 'description': '냉각총으로 5 피해를 준다.'}}},
 {'hero_key': 'ashe',
  'name': '애쉬',
  'role': 'dealer',
  'hp': 12,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 6},
  'skill_meta': {'skill_1': {'name': '바이퍼', 'cooldown': 0, 'description': '바이퍼로 6 피해를 준다.'},
                 'skill_2': {'name': '다이너마이트', 'cooldown': 0, 'description': '한 가로줄에 화상을 부여해 매턴 1 피해를 준다.'}},
  'extra': {'burn_damage': 1, 'burn_duration': 3}},
 {'hero_key': 'soldier76',
  'name': '솔져:76',
  'role': 'dealer',
  'hp': 12,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3, 'skill_2': 6},
  'skill_meta': {'skill_1': {'name': '생체장', 'cooldown': 0, 'description': '같은 가로줄 아군을 3 회복한다. 연속 사용은 불가하다.'},
                 'skill_2': {'name': '펄스 소총', 'cooldown': 0, 'description': '펄스 소총으로 6 피해를 준다.'}}},
 {'hero_key': 'symmetra',
  'name': '시메트라',
  'role': 'dealer',
  'hp': 12,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_2': [2, 4, 8]},
  'skill_meta': {'skill_1': {'name': '순간이동기', 'cooldown': 0, 'description': '아군 또는 자신을 본대와 사이드 사이에서 자유롭게 이동시킨다.'},
                 'skill_2': {'name': '광자 발사기', 'cooldown': 0, 'description': '같은 대상을 연속 공격할수록 2 → 4 → 8로 피해가 증가한다.'}}},
 {'hero_key': 'torbjorn',
  'name': '토르비욘',
  'role': 'dealer',
  'hp': 14,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 4},
  'skill_meta': {'passive': {'name': '포탑 설치',
                             'description': '옆칸이 비어 있고 본대에 있을 때 포탑을 설치한다. 포탑은 체력 5를 가지며 토르비욘이 공격하는 대상에게 추가 2 피해를 준다.'},
                 'skill_1': {'name': '대못 발사기', 'cooldown': 0, 'description': '대못 발사기로 4 피해를 준다.'},
                 'skill_2': {'name': '대장간 망치', 'cooldown': 0, 'description': '대장간 망치로 포탑 체력을 3 회복한다.'}},
  'extra': {'turret_hp': 5, 'turret_damage': 2, 'repair_amount': 3}},
 {'hero_key': 'sojourn',
  'name': '소전',
  'role': 'dealer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3, 'skill_2': [2, 5, 8]},
  'skill_meta': {'skill_1': {'name': '레일건', 'cooldown': 0, 'description': '레일건으로 2 피해를 주고 차징 게이지를 올린다.'},
                 'skill_2': {'name': '차징샷', 'cooldown': 0, 'description': '차징 단계에 따라 2 / 5 / 8 피해를 주는 관통 공격이다.'}}},
 {'hero_key': 'emre',
  'name': '엠레',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': [6, 3]},
  'skill_meta': {'skill_1': {'name': '사이버 파편 수류탄',
                             'cooldown': 0,
                             'description': '대상에게 6 피해를 주고, 이후 랜덤한 적 하나에게 3 피해가 추가로 튕긴다.'}}},
 {'hero_key': 'ana',
  'name': '아나',
  'role': 'healer',
  'hp': 7,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': {'heal': 5, 'damage': 3}},
  'skill_meta': {'skill_1': {'name': '생체 소총', 'cooldown': 0, 'description': '아군에게 사용하면 5 회복, 적에게 사용하면 3 피해를 준다.'}}},
 {'hero_key': 'lucio',
  'name': '루시우',
  'role': 'healer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': {'heal': 2}},
  'skill_meta': {'skill_1': {'name': '볼륨업',
                             'cooldown': 0,
                             'description': '본대에 있으면 같은 영역 아군 전체를 2 회복하고, 사이드에 있으면 같은 영역 아군에게 한 칸 무시 이동형 공격 각을 제공한다.'},
                 'skill_2': {'name': '소리 파동', 'cooldown': 0, 'description': '맞은 상대의 공격 사거리를 1 감소시킨다.'}}},
 {'hero_key': 'kiriko',
  'name': '키리코',
  'role': 'healer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': {'heal': 4, 'damage': 5}},
  'skill_meta': {'passive': {'name': '순보', 'description': '사이드에 있을 때 체력이 4 이하가 되면 본대로 이동한다.'},
                 'skill_1': {'name': '힐부적/쿠나이',
                             'cooldown': 0,
                             'description': '본대에 있으면 힐부적으로 4 회복, 사이드에 있으면 쿠나이로 5 피해를 준다.'}},
  'extra': {'swift_step_threshold': 4}},
 {'hero_key': 'moira',
  'name': '모이라',
  'role': 'healer',
  'hp': 7,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5, 'skill_2': 2},
  'skill_meta': {'skill_1': {'name': '생체 손아귀', 'cooldown': 0, 'description': '충전이 있을 때 같은 세로줄 아군을 5 회복한다.'},
                 'skill_2': {'name': '생체 구슬', 'cooldown': 0, 'description': '생체 구슬로 2 피해를 주고 생체 손아귀의 충전을 1 얻는다.'}}},
 {'hero_key': 'zenyatta',
  'name': '젠야타',
  'role': 'healer',
  'hp': 6,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_2': 3},
  'skill_meta': {'skill_1': {'name': '부조화', 'cooldown': 0, 'description': '한 턴 동안 대상이 받는 피해를 2 증가시킨다.'},
                 'skill_2': {'name': '조화', 'cooldown': 0, 'description': '대상 아군 하나를 3 회복한다.'}},
  'extra': {'discord_value': 2}},
 {'hero_key': 'wuyang',
  'name': '우양',
  'role': 'healer',
  'hp': 7,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_2': 3},
  'skill_meta': {'skill_1': {'name': '수호의 파도',
                             'cooldown': 0,
                             'description': '세로로 선착순 두 칸에 효과를 적용한다. 아군에게는 받는 치유 +2, 적에게는 사거리 -1 또는 넉백 효과를 준다.'},
                 'skill_2': {'name': '회복의 물결', 'cooldown': 0, 'description': '아군 하나를 3 회복한다.'}},
  'extra': {'heal_amplify': 2, 'knockback_value': 1}},
 {'hero_key': 'mizuki',
  'name': '미즈키',
  'role': 'healer',
  'hp': 7,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '속박사슬', 'cooldown': 0, 'description': '상대 사이드 대상 하나를 한 턴 동안 스킬 봉쇄한다.'},
                 'skill_2': {'name': '치유의 삿갓', 'cooldown': 0, 'description': '총 5의 치유량을 현재 아군 수에 맞게 랜덤 분배한다.'}},
  'extra': {'kasa_total_heal': 5}},
 {'hero_key': 'baptiste',
  'name': '바티스트',
  'role': 'healer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3, 'skill_2': 3},
  'skill_meta': {'skill_1': {'name': '생체탄 발사기', 'cooldown': 0, 'description': '같은 가로줄 아군 전체를 3 회복한다.'},
                 'skill_2': {'name': '공격', 'cooldown': 0, 'description': '적 하나에게 3 피해를 준다.'}}},
 {'hero_key': 'mercy',
  'name': '메르시',
  'role': 'healer',
  'hp': 6,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'passive': {'name': '부활', 'description': 'TRASH의 카드 1장을 소생시킨다.'},
                 'skill_1': {'name': '카두세우스 지팡이', 'cooldown': 0, 'description': '카두세우스 지팡이로 연결된 대상을 3 회복한다.'}}},
 {'hero_key': 'brigitte',
  'name': '브리기테',
  'role': 'healer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'passive': {'name': '격려', 'description': '매턴 주위 아군을 1 회복한다.'},
                 'skill_1': {'name': '수리팩', 'cooldown': 0, 'description': '거리 제한 없이 아군 하나를 3 회복한다.'}},
  'extra': {'inspire_heal': 1}},
 {'hero_key': 'illari',
  'name': '일리아리',
  'role': 'healer',
  'hp': 6,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'passive': {'name': '힐 포탑', 'description': '힐러 칸을 차지하는 포탑을 생성하며, 가장 체력이 낮은 아군을 3 회복한다. 포탑 체력은 3이다.'},
                 'skill_1': {'name': '태양 소총', 'cooldown': 0, 'description': '태양 소총으로 5 피해를 준다.'}},
  'extra': {'turret_hp': 3, 'turret_heal': 3}},
 {'hero_key': 'juno',
  'name': '주노',
  'role': 'healer',
  'hp': 6,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'passive': {'name': '하이퍼링', 'description': '배치한 턴에 아군의 사거리를 1 증가시킨다.'},
                 'skill_1': {'name': '펄사어뢰', 'cooldown': 0, 'description': '사이드/본대와 무관하게 같은 열 아군 모두를 3 회복한다.'}}},
 {'hero_key': 'jetpack_cat',
  'name': '제트팩 캣',
  'role': 'healer',
  'hp': 6,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'passive': {'name': '생명줄', 'description': '연결된 대상이 살아 있는 동안 자동 비행 보조가 유지되고 공격 사거리를 1 증가시킨다.'},
                 'skill_1': {'name': '생체 냥냥탄', 'cooldown': 0, 'description': '연결 대상이 사라졌을 때 사용 가능하며, 아군 하나를 3 회복한다.'}}},
 {'hero_key': 'spell_thorn_volley',
  'name': '가시 소나기',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '가시 소나기', 'description': '한 세로줄의 모든 적 스킬을 봉쇄한다.'}}},
 {'hero_key': 'spell_blizzard',
  'name': '눈보라',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '눈보라', 'description': '한 가로줄 전체를 한 턴 동안 빙결 상태로 만든다. 빙결 중에는 무적이며 행동할 수 없고 앞라인도 막지 못한다.'}}},
 {'hero_key': 'spell_gravity_flux',
  'name': '중력붕괴',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '중력붕괴', 'description': '사이드 또는 본대 중 한 영역의 모든 적을 턴 종료시까지 에어본 상태로 만들고, 턴 종료 시 최대체력의 절반(반올림) 피해를 준다.'}}},
 {'hero_key': 'spell_earthshatter',
  'name': '대지분쇄',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '대지분쇄', 'description': '사이드 또는 본대 중 한 영역의 모든 적 스킬을 봉쇄한다.'}}},
 {'hero_key': 'spell_biotic_grenade',
  'name': '생체 수류탄',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 2},
  'skill_meta': {'skill_1': {'name': '생체 수류탄', 'description': '한 영역 전체에 2 피해를 주고 힐밴을 부여한다.'}}},
 {'hero_key': 'spell_rescue',
  'name': '구원의 손길',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '구원의 손길', 'description': 'TRASH에서 카드 1장을 골라 패로 가져온다.'}}},
 {'hero_key': 'spell_sound_barrier',
  'name': '소리방벽',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '소리방벽', 'description': '모든 아군에게 2턴 동안 지속되는 추가 체력 20을 부여한다.'}},
  'extra': {'extra_hp': 20, 'duration': 2}},
 {'hero_key': 'spell_amp_matrix',
  'name': '증폭 매트릭스',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '증폭 매트릭스', 'description': '한 턴 동안 아군의 모든 딜량과 힐량을 2배로 만든다.'}}},
 {'hero_key': 'spell_nano_boost',
  'name': '나노 강화제',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '나노 강화제', 'description': '아군 1명의 공격력을 50% 올리고 받는 피해를 50% 줄인다. 영구 효과다.'}}},
 {'hero_key': 'spell_bob',
  'name': 'B.O.B',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': 'B.O.B', 'description': '탱커 위치에 체력 30의 B.O.B를 배치한다.'}},
  'extra': {'bob_hp': 30}},
 {'hero_key': 'spell_duplicate',
  'name': '복제',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '복제', 'description': '상대 카드 하나를 복제해 내 필드에 소환한다. 해당 역할군 자리가 없으면 사용할 수 없다.'}}},
 {'hero_key': 'spell_riptire',
  'name': '죽이는 타이어',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 15},
  'skill_meta': {'skill_1': {'name': '죽이는 타이어', 'description': '대상 하나에게 15 피해를 준다.'}}},
 {'hero_key': 'spell_seismic_slam',
  'name': '지각 충격',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'skill_1': {'name': '지각 충격', 'description': '상대 필드 전체에 5 피해를 준다.'}}},
 {'hero_key': 'spell_dragonblade',
  'name': '갈라내는 칼날',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 7},
  'skill_meta': {'skill_1': {'name': '갈라내는 칼날', 'description': '한 세로줄 전체에 즉시 7 피해를 준다.'}}},
 {'hero_key': 'spell_orbital_ray',
  'name': '궤도 광선',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '궤도 광선', 'description': '모든 아군을 3 회복하고 한 턴 동안 공격력을 2 증가시킨다.'}},
  'extra': {'heal': 3, 'attack_buff': 2}},
 {'hero_key': 'spell_emp',
  'name': 'EMP',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': 'EMP', 'description': '상대의 설치 카드 효과를 모두 비활성화한다.'}}},
 {'hero_key': 'spell_maximilian',
  'name': '막시밀리앙',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '막시밀리앙', 'description': '덱에서 원하는 카드 1장을 찾아 패로 가져온다.'}}},
 {'hero_key': 'spell_sleep_dart',
  'name': '수면총',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '수면총', 'description': '상대 카드 1장을 한 턴 동안 행동 불가 상태로 만든다.'}}},
 {'hero_key': 'spell_immortality_field',
  'name': '불사장치',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '불사장치', 'description': '아군에게 숨김 부착된다. 2턴 동안 치명 피해를 받아도 체력을 1 남긴다.'}}},
 {'hero_key': 'spell_deflect',
  'name': '튕겨내기',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '튕겨내기', 'description': '아군에게 숨김 부착된다. 치명적인 공격을 받을 때 그 피해를 반사한다.'}}},
 {'hero_key': 'spell_steel_trap',
  'name': '강철 덫',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 4},
  'skill_meta': {'skill_1': {'name': '강철 덫', 'description': '상대 빈칸에 설치된다. 배치된 적에게 4 피해를 주고 한 턴 더 비활성화시킨다.'}}},
 {'hero_key': 'spell_caduceus_staff',
  'name': '카두세우스 지팡이',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '카두세우스 지팡이', 'description': '아군에게 공개 부착되며 공격력을 3 증가시킨다.'}},
  'extra': {'attack_bonus': 3}}]


async def seed_cards(db: AsyncSession):
    result = await db.execute(select(CardTemplate).limit(1))
    if result.scalar_one_or_none():
        return
    for card_data in SEED_CARDS:
        db.add(CardTemplate(**card_data))
    await db.commit()
    print(f"[SEED] {len(SEED_CARDS)} cards inserted.")
