"""초기 카드 시드 데이터 (skill_meta.description 기반 버전)."""
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from models.card import CardTemplate

SEED_CARDS = [{'hero_key': 'reinhardt',
  'name': '라인하르트',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'passive': {'name': '방벽 방패', 'description': '내구도 15의 도발 방벽을 전개합니다.'},
                 'skill_1': {'name': '화염강타', 'cooldown': 0, 'description': '방벽을 무시하는 불타는 투사체를 날립니다.'}},
  'extra': {'barrier_hp': 15}},
 {'hero_key': 'winston',
  'name': '윈스턴',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 4},
  'skill_meta': {'skill_1': {'name': '테슬라 캐논', 'cooldown': 0, 'description': '가로줄 단위의 광역 피해를 줍니다.'},
                 'skill_2': {'name': '방벽 생성기', 'cooldown': 0, 'description': '내구도 5의 영구 방벽을 자신 또는 다른 아군 역할군에 부여합니다.'}},
  'extra': {'barrier_hp': 5}},
 {'hero_key': 'dva',
  'name': '디바',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5, 'skill_2': [8, 5, 3]},
  'skill_meta': {'passive': {'name': '메카 파괴', 'description': '메카가 파괴되면 송하나가 소환됩니다.'},
                 'skill_1': {'name': '부스터',
                             'cooldown': 0,
                             'description': '거리 1을 패싱하고 공격을 할 수 있습니다. 다음 턴에는 무시 상태가 됩니다.'},
                 'skill_2': {'name': '마이크로 미사일', 'cooldown': 0, 'description': '거리별 공격력 감소가 적용됩니다.'}},
  'extra': {'hana_hp': 5}},
 {'hero_key': 'zarya',
  'name': '자리야',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 0, 'skill_2': 5},
  'skill_meta': {'skill_1': {'name': '입자 방벽',
                             'cooldown': 0,
                             'description': '공격 1회를 무효화합니다. 피격 시 다음 턴 입자포 피해가 3 증가하며, 공격받지 않으면 1턴 후 파괴됩니다.'},
                 'skill_2': {'name': '입자포', 'cooldown': 0, 'description': '입자 방벽이 공격받으면 강화된 공격을 가합니다.'}},
  'extra': {'particle_bonus': 3}},
 {'hero_key': 'wrecking_ball',
  'name': '레킹볼',
  'role': 'tank',
  'hp': 25,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 4, 'skill_2': 6},
  'skill_meta': {'skill_1': {'name': '갈고리',
                             'cooldown': 0,
                             'description': '사용 시 본대와 사이드 간 위치를 이동합니다.'},
                 'skill_2': {'name': '파일드라이버',
                             'cooldown': 0,
                             'description': '대상에게 에어본 효과를 부여합니다.'}}},
 {'hero_key': 'junkerqueen',
  'name': '정커퀸',
  'role': 'tank',
  'hp': 22,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'skill_1': {'name': '톱니칼', 'cooldown': 0, 'description': '대상의 거리를 1 끌어당깁니다.'},
                 'skill_2': {'name': '지휘의 외침', 'cooldown': 0, 'description': '주위 아군에게 추가 체력 2를 부여합니다.', 'duration': 2}},
  'extra': {'shout_extra_hp': 2}},
 {'hero_key': 'doomfist',
  'name': '둠피스트',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': [5, 3], 'skill_1_empowered': 6},
  'skill_meta': {'skill_1': {'name': '로켓 펀치',
                             'cooldown': 0,
                             'description': '뒤 한 칸의 대상에게 3 피해를 주며, 강화 상태라면 둘 모두에게 6 피해를 줍니다.'},
                 'skill_2': {'name': '파워블락', 'cooldown': 0, 'description': '공격으로부터 자신을 방어합니다. 로켓 펀치가 강화됩니다.'}},
  'extra': {'block_reduction': 50}},
 {'hero_key': 'sigma',
  'name': '시그마',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '실험용 방벽', 'cooldown': 0, 'description': '도발 효과를 지닌 내구도 10의 방벽을 설치하거나 내릴 수 있음.(파괴됐을시 초재생을 통해 내구도 회복)'},
                 'skill_2': {'name': '초재생', 'cooldown': 0, 'description': '방벽 내구도 5를 회복합니다.'}},
  'extra': {'barrier_hp': 10, 'regen_amount': 5}},
 {'hero_key': 'ramattra',
  'name': '라마트라',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 2},
  'skill_meta': {'skill_1': {'name': '탐식의 소용돌이',
                             'cooldown': 0,
                             'description': '한 가로줄에 3의 광역딜을 준다.'},
                 'skill_2': {'name': '폼 체인지',
                             'cooldown': 0,
                             'description': '일반 폼과 네메시스 폼을 전환한다. 네메시스 폼 전환 시 추가 체력을 얻는다.'},
                 'skill_3': {'name': '막기', 'cooldown': 0, 'description': '50% 피해감소 효과를 받는다.'}},
  'extra': {'nemesis_bonus_hp': 10, 'block_reduction': 50}},
 {'hero_key': 'domina',
  'name': '도미나',
  'role': 'tank',
  'hp': 22,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'skill_1': {'name': '수정 발사', 'cooldown': 0, 'description': '탱커를 무시하고 상대 딜러 라인 전체에 3 피해를 줍니다.'},
                 'skill_2': {'name': '방벽 배열', 'cooldown': 0, 'description': '내구도 4의 도발 방벽을 배열합니다.'}},
  'extra': {'barrier_hp': 4}},
 {'hero_key': 'roadhog',
  'name': '로드호그',
  'role': 'tank',
  'hp': 25,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 0, 'skill_2': 5},
  'skill_meta': {'skill_1': {'name': '갈고리',
                             'cooldown': 0,
                             'description': '한 칸 먼 거리의 적까지 끌어당깁니다. 적중한 대상은 그 턴 동안 사거리와 무관하게 아군이 공격할 수 있습니다.'},
                 'skill_2': {'name': '숨돌리기', 'cooldown': 0, 'description': '체력이 15 이하일 때 사용 가능하며 체력을 5 회복합니다.'}},
  'extra': {'heal_threshold': 15}},
 {'hero_key': 'mauga',
  'name': '마우가',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3, 'skill_2': 3},
  'skill_meta': {'passive': {'name': '터질듯한 심장', 'description': '화상 상태의 적 공격 시, 피해의 50%만큼 체력을 회복합니다.'},
                 'skill_1': {'name': '화염기관포 거니', 'cooldown': 0, 'description': '화상을 입힙니다.'},
                 'skill_2': {'name': '촉발기관포 차차', 'cooldown': 0, 'description': '대상이 화상 상태면 2배 피해를 줍니다.'}},
  'extra': {'burn_damage': 2, 'burn_duration': 3, 'lifesteal_vs_burn_ratio': 0.5}},
 {'hero_key': 'orisa',
  'name': '오리사',
  'role': 'tank',
  'hp': 22,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'passive': {'name': '방어강화', 'description': '체력이 10 이하가 되면 지정된 디버프를 즉시 해제하고, 모든 상태이상에 면역이 되며 받는 피해가 50% 감소합니다.'},
                 'skill_1': {'name': '투창', 'cooldown': 0, 'description': '뒤에 적이 있다면, 2의 피해를 더 줍니다.'}},
  'extra': {'fortify_damage_reduction': 50, 'fortify_clear_debuffs': ['knockback', 'pulled', 'frozen_state', 'burn', 'discord', 'heal_block', 'skill_silence', 'hooked', 'gravity_flux_airborne', 'airborne']}},
 {'hero_key': 'hazard',
  'name': '해저드',
  'role': 'tank',
  'hp': 20,
  'cost': 2,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_2': 5},
  'skill_meta': {'passive': {'name': '날카로운 저항', 'description': '해저드를 공격한 대상에게 2의 딜을 준다.'},
                 'skill_1': {'name': '가시벽',
                             'cooldown': 2,
                             'description': '상대의 빈 칸에 내구도 6의 가시벽을 설치합니다. 가시벽은 하나만 유지되며, 해당 칸에는 카드를 배치할 수 없습니다.'},
                 'skill_2': {'name': '덤벼들기', 'cooldown': 0, 'description': '대상에게 5 피해를 준다.'}},
  'extra': {'hazard_retaliate': 2, 'hazard_wall_hp': 6, 'hazard_wall_description': '해저드 설치물'}},
 {'hero_key': 'bastion',
  'name': '바스티온',
  'role': 'dealer',
  'hp': 12,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 10, 'skill_2': 2},
  'skill_meta': {'skill_1': {'name': '설정: 강습', 'cooldown': 0, 'description': '연속으로 사용이 불가합니다.'},
                 'skill_2': {'name': '설정: 수색', 'cooldown': 0, 'description': '다음 턴에 설정: 강습이 활성화됩니다.'}}},
 {'hero_key': 'freja',
  'name': '프레야',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 0, 'skill_2': 9},
  'skill_meta': {'skill_1': {'name': '상승기류',
                             'cooldown': 0,
                             'description': '에어본 상태가 됩니다.'},
                 'skill_2': {'name': '정조준', 'cooldown': 0, 'description': '에어본 상태에서만 사용 가능하며, 사용후 착지합니다.'}}},
 {'hero_key': 'pharah',
  'name': '파라',
  'role': 'dealer',
  'hp': 12,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': [5, 3]},
  'skill_meta': {'passive': {'name': '호버 추진기', 'description': '항상 에어본 상태를 유지합니다.'},
                 'skill_1': {'name': '로켓 런처', 'cooldown': 0, 'description': '직격 5, 옆에 있는 적에게 3딜을 주는 광역 공격입니다.'}}}, 
 {'hero_key': 'tracer',
  'name': '트레이서',
  'role': 'dealer',
  'hp': 6,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'passive': {'name': '점멸', 'description': '상대의 거리 한 칸 무시하고 공격할 수 있습니다.'},
                 'skill_1': {'name': '펄스 쌍권총', 'cooldown': 0, 'description': ''},
                 'skill_2': {'name': '역행', 'cooldown': 0, 'description': '한 턴 전 체력 상태로 되돌아간다.'}}},
 {'hero_key': 'widowmaker',
  'name': '위도우메이커',
  'role': 'dealer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 99,
  'description': '',
  'skill_damages': {'skill_1': 4},
  'skill_meta': {'passive': {'name': '명사수', 'description': '거리의 영향을 받지 않고 공격할 수 있습니다.'},
                 'skill_1': {'name': '죽음의 입맞춤',
                             'cooldown': 0,
                             'description': '동전을 두 개 던져, 둘 다 앞면이 뜨면 헤드샷이 발동해 3배 피해를 줍니다.'}}},
 {'hero_key': 'hanzo',
  'name': '한조',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 99,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'passive': {'name': '명사수', 'description': '거리의 영향을 받지 않고 공격할 수 있습니다.'},
                 'skill_1': {'name': '폭풍활', 'cooldown': 0, 'description': '동전을 두 개 던져, 둘 다 앞면이 뜨면 헤드샷이 발동해 2배 피해를 줍니다.'}}},
 {'hero_key': 'venture',
  'name': '벤처',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 7, 'skill_2': 3},
  'skill_meta': {'skill_1': {'name': '잠복',
                             'cooldown': 0,
                             'description': '잠복 상태가 되고 다음턴에 공격합니다.'},
                 'skill_2': {'name': '스마트 굴착기', 'cooldown': 0, 'description': ''}}},
 {'hero_key': 'vendetta',
  'name': '벤데타',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 6},
  'skill_meta': {'passive': {'name': '빠른 복수',
                             'description': '피격 시 공격한 적에게 표적을 남깁니다. 표적이 남겨진 대상은 벤데타에게 거리와 무관하게 공격당하며 2 추가 피해를 받는다.'},
                 'skill_1': {'name': '치솟는 베기', 'cooldown': 0, 'description': '표적 상태 대상에게는 패시브 추가 피해가 적용됩니다.'}},
  'extra': {'vendetta_mark_duration': -1, 'vendetta_mark_bonus_damage': 2}},
 {'hero_key': 'sombra',
  'name': '솜브라',
  'role': 'dealer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5, 'skill_2': {'duration': 2}},
  'skill_meta': {'passive': {'name': '은신', 'description': '배치 시 4턴 동안 은신 상태가 된다.'},
                 'skill_1': {'name': '기관단총', 'cooldown': 0, 'description': ''},
                 'skill_2': {'name': '해킹', 'cooldown': 0, 'description': '대상을 해킹해 스킬 사용을 봉쇄합니다. 연속 사용이 불가합니다.'}},
  'extra': {'passive_stealth_duration': 4}},
 {'hero_key': 'echo',
  'name': '에코',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': [4, 4], 'skill_2': 6},
  'skill_meta': {'skill_1': {'name': '점착폭탄', 'cooldown': 0, 'description': '점착 피해 4를 주고 다음 턴에 폭발 피해 4를 줍니다.'},
                 'skill_2': {'name': '광선집중', 'cooldown': 0, 'description': '생명력이 절반 이하인 적들에게 1.5배 피해를 줍니다.'}}},
 {'hero_key': 'cassidy',
  'name': '캐서디',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 3,
  'description': '',
  'skill_damages': {'skill_1': [7, 5, 3]},
  'skill_meta': {'skill_1': {'name': '난사', 'cooldown': 0, 'description': '거리별 공격력 감소가 적용됩니다.'}}},
 {'hero_key': 'reaper',
  'name': '리퍼',
  'role': 'dealer',
  'hp': 12,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 3,
  'description': '',
  'skill_damages': {'skill_1': [8, 4, 2]},
  'skill_meta': {'skill_1': {'name': '헬파이어 샷건', 'cooldown': 0, 'description': '거리별 공격력 감소가 적용됩니다.'}}},
 {'hero_key': 'mei',
  'name': '메이',
  'role': 'dealer',
  'hp': 15,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'passive': {'name': '급속 빙결',
                             'description': '치명 피해를 받으면 빙결 상태가 되며, 다음 자신의 턴 시작 시 체력을 50% 회복하고 빙결이 해제됩니다.'},
                 'skill_1': {'name': '냉각총', 'cooldown': 0, 'description': ''}}},
 {'hero_key': 'ashe',
  'name': '애쉬',
  'role': 'dealer',
  'hp': 12,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 6},
  'skill_meta': {'skill_1': {'name': '바이퍼', 'cooldown': 0, 'description': ''},
                 'skill_2': {'name': '다이너마이트', 'cooldown': 0, 'description': '상대의 한 가로줄에게 화상을 입힙니다.'}},
  'extra': {'burn_damage': 2, 'burn_duration': 3}},
 {'hero_key': 'anran',
  'name': '안란',
  'role': 'dealer',
  'hp': 9,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 4, 'skill_2': 2},
  'skill_meta': {'skill_1': {'name': '불난 데 부채질', 'cooldown': 0, 'description': '대상이 화상 상태라면 2배 피해를 줍니다.'},
                 'skill_2': {'name': '맹염 질주', 'cooldown': 0, 'description': '화상을 입힙니다.'}},
  'extra': {'burn_damage': 2, 'burn_duration': 3}},
 {'hero_key': 'soldier76',
  'name': '솔져:76',
  'role': 'dealer',
  'hp': 12,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3, 'skill_2': 6},
  'skill_meta': {'skill_1': {'name': '생체장', 'cooldown': 0, 'description': '같은 가로줄 아군을 3 회복합니다.'},
                 'skill_2': {'name': '펄스 소총', 'cooldown': 0, 'description': ''}}},
 {'hero_key': 'symmetra',
  'name': '시메트라',
  'role': 'dealer',
  'hp': 12,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_2': [2, 4, 8]},
  'skill_meta': {'skill_1': {'name': '순간이동기', 'cooldown': 0, 'description': '아군 또는 자신을 본대와 사이드 사이에서 자유롭게 이동시킬 수 있습니다.'},
                 'skill_2': {'name': '광자 발사기', 'cooldown': 0, 'description': '같은 대상을 연속 공격할수록 피해가 증가합니다.'}}},
 {'hero_key': 'torbjorn',
  'name': '토르비욘',
  'role': 'dealer',
  'hp': 14,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 4},
  'skill_meta': {'passive': {'name': '포탑 설치',
                             'description': '토르비욘이 공격하는 대상에게 추가 2 피해를 주는 포탑을 설치합니다. 포탑은 옆칸이 차있다면 설치되지 않습니다.'},
                 'skill_1': {'name': '대못 발사기', 'cooldown': 0, 'description': ''},
                 'skill_2': {'name': '대장간 망치', 'cooldown': 0, 'description': '포탑 체력을 3 수리합니다.'}},
  'extra': {'turret_hp': 5, 'turret_damage': 2, 'turret_description': '내 턴 시작 시 가까운 적 1명에게 자동 공격.', 'repair_amount': 3}},
 {'hero_key': 'sojourn',
  'name': '소전',
  'role': 'dealer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3, 'skill_2': [2, 5, 8]},
  'skill_meta': {'skill_1': {'name': '레일건', 'cooldown': 0, 'description': '피해를 주고 에너지를 생성해 차징 게이지를 올립니다.'},
                 'skill_2': {'name': '차징샷', 'cooldown': 0, 'description': '차징 단계에 따라 저장된 에너지를 소모하여 적을 꿰뚫는 강력한 사격을 가합니다.'}}},
 {'hero_key': 'junkrat',
  'name': '정크랫',
  'role': 'dealer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': [6, 3]},
  'skill_meta': {'skill_1': {'name': '폭탄 발사기',
                             'cooldown': 0,
                             'description': '대상에게 6 피해를 주고, 수류탄이 한 번 튕겨 랜덤한 적 하나에게 3 피해를 준다.'}}},
 {'hero_key': 'emre',
  'name': '엠레',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 6},
  'skill_meta': {'skill_1': {'name': '사이펀 블라스터',
                             'cooldown': 0,
                             'description': '피해의 50%만큼 체력을 회복합니다.'}}},
  {'hero_key': 'genji',
  'name': '겐지',
  'role': 'dealer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 4},
  'skill_meta': {'skill_1': {'name': '질풍참',
                             'cooldown': 0,
                             'description': '처치에 성공하면 질풍참을 즉시 한 번 더 사용합니다.'}}},
 {'hero_key': 'ana',
  'name': '아나',
  'role': 'healer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': {'heal': 6, 'damage': 3}},
  'skill_meta': {'skill_1': {'name': '생체 소총', 'cooldown': 0, 'description': '아군은 치유하고 적에게는 피해를 주는 원거리 소총입니다.'}}},
 {'hero_key': 'lucio',
  'name': '루시우',
  'role': 'healer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': {'heal': 3}},
  'skill_meta': {'skill_1': {'name': '볼륨업',
                             'cooldown': 0,
                             'description': '본대에 있으면 같은 영역에 광역힐을 주고, 사이드에 있다면 같은 영역에 거리가 1 증가하는 이속버프를 줍니다.'},
                 'skill_2': {'name': '소리 파동', 'cooldown': 0, 'description': '거리 제한 없이 대상을 밀어내고 공격 사거리를 1 감소시킵니다.'}}},
 {'hero_key': 'kiriko',
  'name': '키리코',
  'role': 'healer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': {'heal': 5, 'damage': 5}},
  'skill_meta': {'passive': {'name': '순보', 'description': '사이드에서 체력 4 이하 시 본대로 순간이동합니다.'},
                 'skill_1': {'name': '힐부적/쿠나이',
                             'cooldown': 0,
                             'description': '본대에 있으면 치유의 부적으로 힐을, 사이드에 있으면 쿠나이로 피해를 줍니다.'}},
  'extra': {'swift_step_threshold': 4}},
 {'hero_key': 'moira',
  'name': '모이라',
  'role': 'healer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 7, 'skill_2': 3},
  'skill_meta': {'skill_1': {'name': '생체 손아귀', 'cooldown': 0, 'description': '게이지가 충전되어 있을 때 같은 세로줄의 아군을 7 회복합니다. 사용 후에는 게이지를 다시 충전해야 합니다.'},
                 'skill_2': {'name': '생체 구슬', 'cooldown': 0, 'description': '생체 구슬로 피해를 주고 생체 손아귀의 게이지를 회복합니다.'}}},
 {'hero_key': 'zenyatta',
  'name': '젠야타',
  'role': 'healer',
  'hp': 7,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_2': 3},
  'skill_meta': {'skill_1': {'name': '부조화', 'cooldown': 0, 'description': '적에게 구슬을 부착해 받는 피해를 4 증가시킵니다.'},
                 'skill_2': {'name': '조화', 'cooldown': 0, 'description': '아군에게 구슬을 부착해 치유합니다.'}},
  'extra': {'discord_value': 4}},
 {'hero_key': 'wuyang',
  'name': '우양',
  'role': 'healer',
  'hp': 7,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_2': 4},
  'skill_meta': {'skill_1': {'name': '수호의 파도',
                             'cooldown': 0,
                             'description': '세로로 선착순 두 칸에 효과를 적용한다. 아군에게는 받는 치유 +2, 적에게는 사거리 -1 또는 넉백 효과를 준다.'},
                 'skill_2': {'name': '회복의 물결', 'cooldown': 0, 'description': '아군 하나를 3 회복한다.'}},
  'extra': {'heal_amplify': 2, 'knockback_value': 1}},
 {'hero_key': 'mizuki',
  'name': '미즈키',
  'role': 'healer',
  'hp': 7,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '속박사슬', 'cooldown': 0, 'description': '상대 사이드 대상 1명의 스킬을 1턴 동안 봉쇄합니다.'},
                 'skill_2': {'name': '치유의 삿갓', 'cooldown': 0, 'description': '총 5의 치유량을 아군에게 무작위로 분배합니다.'}},
  'extra': {'kasa_total_heal': 5}},
 {'hero_key': 'baptiste',
  'name': '바티스트',
  'role': 'healer',
  'hp': 8,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 4, 'skill_2': 4},
  'skill_meta': {'skill_1': {'name': '생체탄 발사기', 'cooldown': 0, 'description': '한 가로줄의 아군을 4 회복합니다.'},
                 'skill_2': {'name': '3연발 기관단총', 'cooldown': 0, 'description': ''}}},
 {'hero_key': 'mercy',
  'name': '메르시',
  'role': 'healer',
  'hp': 6,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'passive': {'name': '부활', 'description': 'TRASH의 카드 1장을 부활시킵니다.'},
                 'skill_1': {'name': '카두세우스 지팡이', 'cooldown': 0, 'description': ''}}},
 {'hero_key': 'brigitte',
  'name': '브리기테',
  'role': 'healer',
  'hp': 10,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 2},
  'skill_meta': {'passive': {'name': '격려', 'description': '매턴 주위 아군을 2 치유합니다.'},
                 'skill_1': {'name': '수리팩', 'cooldown': 0, 'description': '아군 하나를 2 회복합니다.'}},
  'extra': {'inspire_heal': 2}},
 {'hero_key': 'illari',
  'name': '일리아리',
  'role': 'healer',
  'hp': 6,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 4},
  'skill_meta': {'passive': {'name': '힐 포탑', 'description': '가장 체력이 낮은 아군에게 3힐을 주는 포탑을 설치합니다. 포탑은 옆칸이 차있다면 설치되지 않습니다.'},
                 'skill_1': {'name': '태양 소총', 'cooldown': 0, 'description': ''}},
  'extra': {'turret_hp': 3, 'turret_heal': 3, 'pylon_description': '내 턴 시작 시 가장 체력이 낮은 아군 1명 치유.'}},
 {'hero_key': 'juno',
  'name': '주노',
  'role': 'healer',
  'hp': 6,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'passive': {'name': '하이퍼링', 'description': '배치한 턴에 아군의 사거리를 1 증가시키는 이속 버프를 줍니다.'},
                 'skill_1': {'name': '펄사어뢰', 'cooldown': 0, 'description': '사이드/본대와 무관하게 같은 열 아군 모두를 3 회복합니다.'}}},
 {'hero_key': 'jetpack_cat',
  'name': '제트팩 캣',
  'role': 'healer',
  'hp': 6,
  'cost': 1,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 1,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'passive': {'name': '생명줄', 'description': '제트팩 캣을 배치할 때 개체값1의 카드 1장을 추가로 배치할 수 있습니다.'},
                 'skill_1': {'name': '생체 냥냥탄', 'cooldown': 0, 'description': ''}}},
 {'hero_key': 'spell_thorn_volley',
  'name': '가시 소나기',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'skill_1': {'name': '가시 소나기', 'description': '한 세로줄의 모든 적 스킬을 봉쇄하고 3 피해를 준다. (상대는 스펠만 사용 가능)'}}},
 {'hero_key': 'spell_blizzard',
  'name': '눈보라',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '눈보라', 'description': '한 가로줄 전체를 한 턴 동안 빙결 상태로 만든다. 빙결 중에는 무적이며 행동할 수 없고 앞라인도 막지 못한다.'}}},
 {'hero_key': 'spell_gravity_flux',
  'name': '중력붕괴',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '중력붕괴', 'description': '사이드 또는 본대 중 한 영역의 모든 적을 턴 종료시까지 에어본 상태로 만들고, 턴 종료 시 최대체력의 절반(반올림) 피해를 준다.'}}},
 {'hero_key': 'spell_earthshatter',
  'name': '대지분쇄',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '대지분쇄', 'description': '사이드 또는 본대 중 한 영역의 모든 적 스킬을 봉쇄한다.'}}},
 {'hero_key': 'spell_biotic_grenade',
  'name': '생체 수류탄',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 2},
  'skill_meta': {'skill_1': {'name': '생체 수류탄',
                             'description': '대상 영역이 적이면 2 피해 + 힐밴, 아군이면 6 즉발 치유 후 힐 증폭 부여.',
                             'heal_block_duration': 1,
                             'ally_heal': 6,
                             'heal_amplify_value': 4,
                             'heal_amplify_duration': 1}}},
 {'hero_key': 'spell_rescue',
  'name': '구원의 손길',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '구원의 손길', 'description': 'TRASH에서 카드 1장을 골라 패로 가져온다.'}}},
 {'hero_key': 'spell_sound_barrier',
  'name': '소리방벽',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '소리방벽', 'description': '모든 아군에게 2턴 동안 지속되는 추가 체력 20을 부여한다.'}},
  'extra': {'extra_hp': 20, 'duration': 2}},
 {'hero_key': 'spell_amp_matrix',
  'name': '증폭 매트릭스',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '증폭 매트릭스', 'description': '한 턴 동안 아군의 모든 딜량과 힐량을 2배로 만든다.'}},
  'extra': {'damage_multiplier': 2.0, 'heal_multiplier': 2.0, 'duration': 1}},
 {'hero_key': 'spell_nano_boost',
  'name': '나노 강화제',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '나노 강화제', 'description': '아군 1명의 공격력을 50% 올리고 받는 피해를 50% 줄인다. 영구 효과다.'}},
 'extra': {'damage_multiplier': 1.5, 'damage_reduction': 50, 'duration': -1}},
 {'hero_key': 'spell_bob',
  'name': 'B.O.B',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': 'B.O.B', 'description': '탱커 위치에 체력 30의 B.O.B를 배치한다.'}},
  'extra': {'bob_hp': 30}},
 {'hero_key': 'spell_duplicate',
  'name': '복제',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '복제', 'description': '상대 카드 하나를 복제해 내 필드에 소환한다. 해당 역할군 자리가 없으면 사용할 수 없다.'}}},
 {'hero_key': 'spell_riptire',
  'name': '죽이는 타이어',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 15},
  'skill_meta': {'skill_1': {'name': '죽이는 타이어', 'description': '대상 하나에게 15 피해를 준다.'}}},
 {'hero_key': 'spell_seismic_slam',
  'name': '지각 충격',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 5},
  'skill_meta': {'skill_1': {'name': '지각 충격', 'description': '상대 필드 전체에 5 피해를 준다.'}}},
 {'hero_key': 'spell_dragonblade',
  'name': '갈라내는 칼날',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 7},
  'skill_meta': {'skill_1': {'name': '갈라내는 칼날', 'description': '한 세로줄 전체에 즉시 7 피해를 준다. 방벽과 추가체력을 전부 파괴한다.'}}},
 {'hero_key': 'spell_orbital_ray',
  'name': '궤도 광선',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '궤도 광선', 'description': '모든 아군을 3 회복하고 한 턴 동안 공격력을 2 증가시킨다.'}},
  'extra': {'heal': 3, 'attack_buff': 2}},
 {'hero_key': 'spell_emp',
  'name': 'EMP',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': 'EMP', 'description': '상대의 설치 카드 효과를 모두 비활성화한다.'}}},
 {'hero_key': 'spell_purification_bubble',
  'name': '정화의 방울',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 3},
  'skill_meta': {'skill_1': {'name': '정화의 방울',
                             'description': '한 아군 영역에 즉시 치유를 주고 지정된 상태 이상을 제거한다.',
                             'clear_statuses': ['knockback', 'pulled', 'frozen_state', 'burn', 'discord', 'heal_block', 'skill_silence', 'hooked', 'gravity_flux_airborne', 'airborne']}}},
 {'hero_key': 'spell_dancing_flame',
  'name': '춤추는 불꽃',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 2},
  'skill_meta': {'skill_1': {'name': '춤추는 불꽃',
                             'description': '한 적 영역 전체에게 즉시 피해를 주고 화상을 부여한다.',
                             'burn_duration': 2,
                             'burn_damage': 2}}},
 {'hero_key': 'spell_phoenix_rebirth',
  'name': '불사조 부활',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '불사조 부활',
                             'description': '아군에게 숨김 부착된다. 사망 시 부활 준비 상태로 들어가 다음 내 턴 시작에 되살아난다.',
                             'revive_delay_turns': 1}}},
 {'hero_key': 'spell_fox_path',
  'name': '여우길',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '여우길',
                             'description': '한 아군 세로줄에 이속(사거리)과 공격력 버프를 부여한다.',
                             'range_modifier': 1,
                             'range_duration': 2,
                             'attack_buff': 3,
                             'attack_buff_duration': 2}}},
 {'hero_key': 'spell_slaughter',
  'name': '살육',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 4},
  'skill_meta': {'skill_1': {'name': '살육',
                             'description': '한 적 세로줄 전체에 즉시 피해를 주고 힐밴을 부여한다.',
                             'heal_block_duration': 1}}},
 {'hero_key': 'spell_maximilian',
  'name': '막시밀리앙',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '막시밀리앙', 'description': '덱에서 원하는 카드 1장을 찾아 패로 가져온다.'}}},
 {'hero_key': 'spell_sleep_dart',
  'name': '수면총',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '수면총', 'description': '상대 카드 1장을 수면 상태로 만든다. 수면은 스킬을 봉쇄하며 피해를 받으면 즉시 해제된다.', 'sleep_duration': 5}}},
 {'hero_key': 'spell_immortality_field',
  'name': '불사장치',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '불사장치', 'description': '아군에게 숨김 부착된다. 발동 전까지는 영구 대기하며, 발동 후 2턴 동안 치명 피해를 받아도 체력을 1 남긴다.'}}},
 {'hero_key': 'spell_deflect',
  'name': '튕겨내기',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '튕겨내기', 'description': '아군에게 숨김 부착된다. 치명적인 공격을 받을 때 그 피해를 반사한다.'}}},
 {'hero_key': 'spell_steel_trap',
  'name': '강철 덫',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {'skill_1': 4},
  'skill_meta': {'skill_1': {'name': '강철 덫', 'description': '다음 상대가 배치한 첫 적을 2턴간 비활성화시킨다.', 'silence_duration': 2}}},
 {'hero_key': 'spell_caduceus_staff',
  'name': '카두세우스 지팡이',
  'role': 'spell',
  'hp': 0,
  'cost': 1,
  'is_spell': True,
  'base_attack': 0,
  'base_defense': 0,
  'base_attack_range': 0,
  'description': '',
  'skill_damages': {},
  'skill_meta': {'skill_1': {'name': '카두세우스 지팡이', 'description': '아군에게 공개 부착되며 공격력을 3 증가시킨다.'}},
  'extra': {'attack_bonus': 3}}]


async def seed_cards(db: AsyncSession):
    existing_keys_result = await db.execute(select(CardTemplate.hero_key))
    existing_keys = set(existing_keys_result.scalars().all())

    missing_cards = [card_data for card_data in SEED_CARDS if card_data["hero_key"] not in existing_keys]
    if not missing_cards:
        return
    for card_data in missing_cards:
        db.add(CardTemplate(**card_data))
    await db.commit()
    print(f"[SEED] {len(missing_cards)} cards inserted.")
